spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation_tracker?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password  # Change this to your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # This will create or update tables
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /  # Ensure no context path is set

# CORS Configuration (explicitly allow all origins for development)
cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  allow-credentials: true

# JWT Configuration
app:
  jwt-secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  jwt-expiration-milliseconds: 86400000  # 1 day